### ISSUE TITLE
Add pulp-smash information to the website

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpproject.org#14]
The get involved section should include information about pulp-smash.

**Comment by RCMariko** [comment]
Given the recent changes to move pulp-smash test cases themselves to the Pulp repo - this would be a good opportunity to invite more contributions.

**Comment by mdellweg** [comment]
A guide on how to run the unittests in the devel vagrant box would also be very helpful.

**Comment by lubosmj** [comment]
This is no longer on our radar because we are striving to migrate off pulp-smash.
