### ISSUE TITLE
Create a Pulp calendar on the website

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpproject.org#164]
It would be great to have a public calendar with these types of events on it:

* demos
* triages
* occasional meetups
* booths/talk/workshops--> conferences
* relese announcements dates
* plugin/core/special-interest-group (SIG) meetings

In terms of implementing this, it would be easy to embed a Google calendar into a new page on the website. That Google calendar could be managed by several folks with permissions having management permissions over it. Also using calendar invites would allow third parties to send invitations that approvers could yes/no as well easily.

**Comment by dkliban** [comment]
https://github.com/pulp/pulpproject.org/pull/181

**Comment by dkliban** [comment]
I added Meetings and Upcoming Events to the Get Involved page.
