### ISSUE TITLE
Move Headings to a Drop Down Menu

### ISSUE THREAD

**Issue by CodeHeeler** [pulp/pulpproject.org#182]
Depending on window resizing, we are now reaching a point that we've added enough headings across the top of our site that weird things start happening with the wrapping that needs to occur.

![Screenshot from 2019-03-22 16-14-28](https://user-images.githubusercontent.com/24516652/54850648-10270280-4cbe-11e9-8cdd-8a9a402d2bba.png)

And this is especially true once you reach tablet sizing for the UI

![Screenshot from 2019-03-22 16-16-54](https://user-images.githubusercontent.com/24516652/54850682-28971d00-4cbe-11e9-9b29-b05f9d9b7d1c.png)

How about moving to a dropdown menu, or a couple of them like "Help" and "Get Involved"?

**Comment by melcorr** [comment]
Do you think it might be safe to close this one out? I have created some drop down menus in the last few weeks. On testing this a year or so later, in a Firefox v 77 browser, when I go to squash the window, the topnav disappears and the sidenav is all I can see, which seems not bad.

**Comment by CodeHeeler** [comment]
I'm on the same version now and it looks fine in FF to me and still looks fine on Chrome.  Fine by me.  Thanks for the work you've been doing!
