### ISSUE TITLE
Website and Homepage doesn't clearly advise on state of Pulp2 vs Pulp3

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpproject.org#209]
A user recently pointed out that from pulpproject.org it's difficult to know a few things:

That there are two major versions of Pulp, and the state of readiness of each.
What plugins are available for different versions.

How to find the documentation for what you want from ^ matrix.

In summary, users landing on pulpproject.org are having trouble finding the right docs.

**Comment by mikedep333** [comment]
On [our docs page](https://pulpproject.org/docs/), I think we should explicitly specify the latest stable version number under "Current, Stable" as the link text (rather than having the link text be "docs.pulpproject.org"). This confused me when I first encountered it.

**Comment by melcorr** [comment]
Do you think that with the recent changes we can close this out now @mikedep333 @bmbouter ?

**Comment by bmbouter** [comment]
@melcorr I do think this can be closed. I will close it now. Please reopen or comment if anyone feels we should do so.
