### ISSUE TITLE
As a user, I'd like a prominent link to direct me to the RPMs for the various versions.

### ISSUE THREAD

**Issue by thomasmckay** [pulp/pulpproject.org#23]
My suggestion would be to add a "Download" link in the banner next to "Home" that leads to a page dedicated to pointing to both the download locations (repos.fedorapeople.org) as well as the installation instructions.

This page could also indicate the state of each version as well (released, beta, RC, whatever).

Thanks!

**Comment by lubosmj** [comment]
This is no longer on our radar. We ship PyPI packages and OCI images regularly.
