### ISSUE TITLE
pulpprojects ci banner sais: all is broken when master fails.

### ISSUE THREAD

**Issue by fkuep** [pulp/pulpproject.org#362]
When I browse the github project while master does not "compile" , it looks like there is no working version:  

![image](https://user-images.githubusercontent.com/24989362/122070584-62502300-cdf6-11eb-967a-699e05e62e19.png)

As an unsudpecting user I try to choose ci compliant version and come to the conclusion :  
I should not install any version.

Also: When master is successful, it probably reports success for all branches.

**Comment by melcorr** [comment]
Hey @fkuep - I started a discussion about this over here: https://github.com/pulp/community/discussions/26

**Comment by bmbouter** [comment]
I believe this was resolved with https://github.com/pulp/pulpcore/pull/1413 so I'm going to close. Please post a comment or reopen if not.

**Comment by fkuep** [comment]
Thanks!
