### ISSUE TITLE
change reference from freenode to matrix/libera

### ISSUE THREAD

**Issue by fkuep** [pulp/pulpproject.org#364]
In reference to: [blog anouncment](https://pulpproject.org/2021/06/08/pulp-leaving-freenode/) and [sister issue in pulcore](https://pulp.plan.io/issues/8903)  
*While I don't mind what chat to use, I found contradicting information:*

``` bash
username@hostname:/tmp/pulpproject.org[gh-pages]$ grep  --exclude-dir=_posts -ri freenode
pulp-in-one-container.md:If you experience any problems, check the [Known Issues](/pulp-in-one-container/#known-issues) section for workarounds. If you have any questions, feel free to reach out to us on `pulp-list@redhat.com` or the `#pulp` channel on Freenode IRC.  
username@hostname:/tmp/pulpproject.org[gh-pages]$ 
```

Should these references be change to point to matrix/libera ?

**Comment by melcorr** [comment]
:+1:  Sure @fkuep thank you! 
[would you like a t-shirt?](https://forms.gle/w574hvVykjm5fSmT8)

**Comment by fkuep** [comment]
>  Sure @fkuep thank you!
> [would you like a t-shirt?](https://forms.gle/w574hvVykjm5fSmT8)

What a surprise -  Thank You!

**Comment by melcorr** [comment]
> > Sure @fkuep thank you!
> > [would you like a t-shirt?](https://forms.gle/w574hvVykjm5fSmT8)
> 
> What a surprise - Thank You!
> Are those delivered to the EU ?

Yep :-)
