### ISSUE TITLE
As a user, I can see the new logo and favicon along with a blog post

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpproject.org#38]
The new logo is currently checked in here. It needs to replace to old logo and old favicon. A blog post also should be produced identifying the logo and favicon is changing and thanking our designer. Keeping the new .svg originals along with the new .png files is good needed. The old favicon and .png files should be deleted. Then the organization of the ['images' folder](https://github.com/pulp/pulpproject.org/tree/gh-pages/images/logo) can probably be consolidated also.

- [x] Update the logo to the new logo
- [x] Update the favicon to the new favicon
- [x] Delete the old logo and favicon files
- [x] Ensure the layout of the ['images' folder](https://github.com/pulp/pulpproject.org/tree/gh-pages/images/logo) is sane.
- [x] Write a blog post announcing and displaying the new logo and favicon.

**Comment by daviddavis** [comment]
@bmbouter I'm struggling with what to write for the blog post. Do you have maybe a good idea or outline of what we should include? 

Btw, I went ahead and emailed the designer to ask if we could include her name.

Thanks!

**Comment by bmbouter** [comment]
Ideally the post would be short, but contain things like:

* Identify that a change is being made to the logo and favicon
* A small description of why some of the changes were needed. (hard to read, too text centric, it was time for a change, etc).
* A short description of the new hotness (more of a graphic, more modern look with flat colors, colors selected with colorblindness in mind, better contrast, printable in large and small formats).
