### ISSUE TITLE
Dead links on page pulp-workflow-overview

### ISSUE THREAD

**Issue by xenlo** [pulp/pulpproject.org#417]
Hi,
I found two dead links on line 10 of [pulp-workflow-overview page](https://github.com/pulp/pulpproject.org/blob/736c054f63da7962a051312b81f3fc344fe04ad5/pulp-workflow-overview.md?plain=1#L10).

`/#pulp---from-such-great-heights/` and `/#pulp-for-cicd/` doesn't seems to exist any more.

**Comment by melcorr** [comment]
Hello ! @xenlo merci beaucoup/dank u wel for this! 
I will fix this today <3

**Comment by melcorr** [comment]
I tested and all looks good. 
Thank you again!

**Comment by xenlo** [comment]
Thanks for fast reaction!
