### ISSUE TITLE
Feedback on the pulpproject.org landing page

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulpproject.org#429]
I've been sharing the https://pulpproject.org/ page with people at my org and the landing page is almost completely useless in describing what pulp is and what its value is. 

First, it uses ambiguous words like software packages/consumers/etc instead of concrete examples like rpms/debs/python packages/etc. Software packages could refer to many different things depending on the context.

Second, it would help to maybe give some concrete examples/use cases for things you can do with Pulp. Not sure that descriptions like "managing repositories of software packages" and "making them available to a large number of consumers" really help users to understand what Pulp does, how they might use it, what Pulp's value proposition is, etc.

**Comment by daviddavis** [comment]
Ok, then after the intro paragraph which doesn't give me any reason to use Pulp, it says that Pulp has a REST API. Why bother telling me that if you haven't even sold me on the idea of using Pulp? Also, I am not sure that having a REST API is a big selling point anymore.

**Comment by daviddavis** [comment]
Also it links to the github page, twitter, and youtube. I think discourse and matrix would be more helpful personally. What is a person suppose to do at https://github.com/pulp/? Start reading source code? 

Also, the youtube channel has seen better days. Not sure it's something you want to advertise on the landing page.

**Comment by fao89** [comment]
I'm curious about your opinion on this: https://discourse.pulpproject.org/t/rfc-pulp-101-webpage/155/14
which is selling this 101:
https://melcorr.github.io/pulpproject.org/pulp-workflow-overview/

**Comment by melcorr** [comment]
Hey @daviddavis 
This is great. 
Can't dispute anything you have said. 
This is the only part of the site I haven't worked on at this stage. 
I had a few conversations with different people in different projects that led me to believe that our front page was standard, if not the desired end-state. 
I didn't really understand any of the jargon mentioned in our opening statement either but put it down to engineering inexperience. 
It seems that a lot of effort went into that text at some point as it is essentially the elevator pitch for Pulp as outlined on our wiki brand page. 
@daviddavis  - would you think that it might be a solution to move all the content from Pulp 101 to the main page?

**Comment by daviddavis** [comment]
I think the Pulp 101 page would make a much better landing page than what currently exists. For one thing, I think the diagrams are very helpful in understanding Pulp quickly (especially the first one). 

A couple downsides on having the Pulp 101 page as the landing page though (and again this is totally my personal opinion so feel free to ignore):
* The Pulp 101 page focuses on ***how*** to use Pulp and I feel like the landing page should focus on ***why*** you'd want to use Pulp. They're similar but a bit different.
* I'd expect the landing page's job to sell Pulp. I think concrete use cases would really sell pulp (e.g. "mirror PyPI and serve Python packages locally", "host your own docker registry", "create a repository of linux (deb/rpms) for your company", etc)

**Comment by melcorr** [comment]
OK.. so a Pulp 101 Why page. Leave it with me, I'll put something together. 
One last thing @daviddavis  - do you think that there are other ways of representing Pulp diagramatically that would be helpful ?

**Comment by daviddavis** [comment]
I think the first diagram on the 101 page is solid. Maybe if you had a different icon for the computers instead of laptops though 😁

**Comment by melcorr** [comment]
Point me to the souped up computer of your dreams and I will draw :)

**Comment by daviddavis** [comment]
Maybe like a desktop tower?

<img width="572" alt="image" src="https://user-images.githubusercontent.com/86290/159273108-31ca8d0e-dc53-4394-9f1d-704a149df3fd.png">

**Comment by melcorr** [comment]
Sure thing. I'll draw something and swap it out of all images. I had the Thinkpad in my mind's eye as I was making that drawing.
