### ISSUE TITLE
the link to the 'try-pulp-in-docker' post is dead (404)

### ISSUE THREAD

**Issue by rplevka** [pulp/pulpproject.org#46]
the url for the script to get the pulp deployed in docker is not working anymore.
Not sure, whether it just moved or the procedure has been abandoned.

https://raw.githubusercontent.com/pulp/pulp_packaging/master/dockerfiles/centos/start.sh

https://github.com/pulp/pulpproject.org/blob/52754491acd7e3d9676cb69d58ebf986449e58fe/_posts/2015-05-21-use-docker-to-try-pulp.md#L15

**Comment by rayanimesh** [comment]
@bmbouter : I think the file mentioned above has been moved to https://github.com/pulp/packaging/blob/docker/dockerfiles/centos/start.sh.  
The same has been mentioned [here](https://github.com/pulp/pulp_packaging).

Let me know if this is correct and I will send a PR updating the blog post.

**Comment by bmbouter** [comment]
@rayanimesh you are right that is the right file. Since it's being used by `wget` I think the full URL to use is:  `https://raw.githubusercontent.com/pulp/packaging/docker/dockerfiles/centos/start.sh`

**Comment by bmbouter** [comment]
This was fixed with #66
