### ISSUE TITLE
Add github buttons and banners to the website

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpproject.org#95]
We want to more clearly communicate that Pulp is open source. Having a clear forking opportunity and clear that the code is public on Github should help with that.

https://github.com/blog/273-github-ribbons
https://buttons.github.io/

[Here is an example](http://docs.python-requests.org/en/master/) of a site that does this

**Comment by monotek** [comment]
+1 
searched for ages for the GitHub link...

**Comment by melcorr** [comment]
Do you think something like this could work? https://hackmd.io/@RVSVTAcpTMCTIIsCkGAmMg/ry0CCpPVu 

I tried adding to the menu but it went funny and kinda ruined it every way I tried. 

Top left is allegedly eye-catching from a UX perspective
