### ISSUE TITLE
Add PUPs to our website

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulpproject.org#97]
It isn't easy to browse https://github.com/pulp/pups as compared to our website. We should add a script that updates our website with viewable versions of PUPs like https://www.python.org/dev/peps/.

**Comment by melcorr** [comment]
Hi @daviddavis has anything updated since you posted this? 
Are you OK for me to go ahead and add these? 
Probably would just add them manually.

**Comment by daviddavis** [comment]
@melcorr I'm not sure if we are still using PUPs. So not sure if we should publish these to the website? @pulp/pulp-team thoughts?

**Comment by bmbouter** [comment]
Given that the pup model is no longer used (for over a year, or two now at least), I believe:
* The pup model should be formally retired.
* The decisions it was used to make should be documented in the right places, e.g. docstrings styles moved to docs.pulpproject.org plugin writer docs.

**Comment by melcorr** [comment]
I think enough time has passed without any objection to closing this off. 
@bmbouter @daviddavis I am happy to work on anything that relates to adding necessary guidelines to the website if you can point me to them.

**Comment by bmbouter** [comment]
How can we ...
1) formally retire the pup process?
2) Move the agreed upon things into our docs so we don't loose the commitment to them as we divest from the process?

My take on (1) is that a PUP9 could be created, merged, and then the github repo could be "archived"

My take on (2) is that docs PRs should be opened against pulpcore to add in those various aspects.
